version: '3'

services:
    app:
        container_name: rest-server
        image: rest-server_app
        restart: always
        ports:
            - '3002:3002'
        volumes:
            - .:/app
        depends_on:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - 3003:27017
        volumes:
            - data:/data/db

volumes:
    data: